version: '3.1'

services: 
    mongo:
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_DATABASE=requestLogDb
        ports:
            - 27017:27017
        expose:
            - "27017"   
        networks:
            - backend 
    zookeeper:
        restart: "always"
        image: confluentinc/cp-zookeeper:latest
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000 
        networks:
            - backend 
    kafka:
        restart: "always"
        image: confluentinc/cp-kafka:latest
        depends_on:
            - zookeeper
        ports:
            - 29092:29092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        networks:
            - backend 
    log-server:
        restart: "always"
        build: .
        ports:
            - 10000:10000
        expose:
            - "10000"
        depends_on:
            - kafka
        networks:
            - backend
        environment:
            - mongoURL=mongo
            - kafkaURL=kafka
networks: 
    backend: